### ISSUE TITLE
Выбор видеокарты

### ISSUE THREAD

**Issue by MaxelsS** [SChernykh/vanity_xmr_cuda#3]
Добрый день, Сергей!
Извините, что на русском. Смотрел интервью с вами и узнал, что Вы знаете русский. А для меня писать на английском - это как майнить Монеро в соло на ноутбуке.
Собственно вопрос: можно ли добавить параметр --device n для выбора конкретной видеокарты для работы приложения, или есть какой-то другой вариант запуска на конкретном GPU? Сейчас, чтобы я не пробовал, оно у меня запускается на всех 3-х моих GPU.

PS: Хотел отдельно Вас поблагодарить за p2pool. Его так не хватало в 2017-2020.

**Comment by SChernykh** [comment]
Добавил параметр `-d N` - релиз 1.03
